name: 游 Bug
description: Algo n칚o est치 funcionando corretamente
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 游빒 Problema
      description: O que est치 errado?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 游대 Passos para reproduzir
      placeholder: |
        1. V치 para...
        2. Clique em...
        3. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 游꿢 Comportamento esperado
