name: ğŸš€ Feature
description: Nova funcionalidade ou mÃ³dulo
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: ğŸ“Œ DescriÃ§Ã£o
      description: Explique o que serÃ¡ implementado
      placeholder: Ex. Criar controller para dashboard
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: âœ… CritÃ©rios de Aceite
      description: O que precisa estar pronto para considerar concluÃ­do
      placeholder: |
        - [ ] UI desacoplada da lÃ³gica
        - [ ] Testes passando
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: ğŸ§  Notas TÃ©cnicas
      description: DecisÃµes tÃ©cnicas, referÃªncias, ideias
