name: ğŸ§± Tech / Refactor
description: RefatoraÃ§Ã£o, melhoria tÃ©cnica ou infra
title: "[Tech] "
labels: ["tech"]
body:
  - type: textarea
    id: context
    attributes:
      label: ğŸ“ Contexto
      description: Por que isso Ã© necessÃ¡rio?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: ğŸ› ï¸ SoluÃ§Ã£o proposta
      description: Como serÃ¡ resolvido
